### ISSUE TITLE
ImportError: No module named distcc_pump_c_extensions

### ISSUE THREAD

**Issue by Fungie2134** [distcc/distcc#219]
I am trying to setup a compile cluster. I installed the 2 debs, and tried to build something. OpenCV, not working, Tried to build distcc which use make, and I get this everytime : 
`owner@node:~/distcc$ export DISTCC_POTENTIAL_HOSTS='localhost 192.168.0.53'
owner@node:~/distcc$ pump make -j8 CC=distcc
__________Using distcc-pump from /usr/local/bin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/include_server/include_server.py", line 42, in <module>
    import distcc_pump_c_extensions
ImportError: No module named distcc_pump_c_extensions
__________Expected a socket at '/tmp/distcc-pump.7Q71SE/socket'
__________Could not start distcc-pump include server
__________Warning: distcc-pump include server failed; running unpumped
__________Found 2 available distcc servers
owner@node:~/distcc$`

**Comment by TafThorne** [comment]
Please could you confirm the version of Distcc and whether you used the Debian repository via `apt` to install or if you took the packages from another source?

**Comment by Fungie2134** [comment]
I took the latest version on https://code.google.com/archive/p/distcc/downloads.

**Comment by TafThorne** [comment]
Thank you for confirming that.

**Comment by Fungie2134** [comment]
You're welcome !
I am presently trying building from sources with Github's files.

**Comment by TafThorne** [comment]
Those are probably going to match what you were using.  There was some work done on master though so someone may have repaired things.

**Comment by Fungie2134** [comment]
It's done and getting exactly the same issue. What I tried (on Ubuntu Server 17.04) : 
- The latests debs,
- The included package trough apt, which seems to be up - to - date,
- Building from latest sources.
All had a little issue with /usr/local/bin where pump was unable to find distcc, a simple ln -s solved the problem.

**Comment by afbjorklund** [comment]
@Fungie2134: It looks like you are trying to use python2, with the python3 extensions ?
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/include_server/include_server.py", line 42, in <module>
    import distcc_pump_c_extensions
ImportError: No module named distcc_pump_c_extensions
```

But I'm seeing similar issues as well, so maybe `find_c_extension.sh` needs updating ?
```
__________Using distcc-pump from .
__________Using 1 distcc server in pump mode
ls: cannot access './_include_server/lib.*/include_server/distcc_pump_c_extensions.[sd][ol]*': No such file or directory
__________Could not find shared libraries for distcc-pump
```

i.e. it fails to find _include_server/lib.linux-x86_64-3.5/include_server/distcc_pump_c_extensions.cpython-35m-x86_64-linux-gnu.so too... But anyway, master now requires python3 rather than python2, so it seems to be looking in the wrong place.

But a fix is needed for [PEP-3149](https://www.python.org/dev/peps/pep-3149/), to add another wildcard (or something) to the library search.

**Comment by afbjorklund** [comment]
e.g. fdc38dfdb2c71aeaa786a7a68cc5af2931d4c744

Does this fix your issue ? Then again, 3.2rc1 "should" have worked, since it still used `python`.
