### ISSUE TITLE
distccd stops accepting connections when using embedded stats server with socat (Also, document the distcc stats server function and usage)

### ISSUE THREAD

**Issue by timblaktu** [distcc/distcc#275]
The stats server embedded in distccd is mentioned in the OPTIONS section of the distccd man page:

```
       --stats
              Turn on the statistics HTTP server. By default it is off.  (Daemon mode only.)

       --stats-port PORT
              Set the TCP port to listen on for HTTP requests, rather than the default of 3633.  (Daemon mode only.)
```

However I can find no description of the actual function of this or expected client usage anywhere on the internet, save for the [distcc source code itself](https://github.com/distcc/distcc/blob/0dd9f05f88281ff4309bbd4c671e112a6ce2a57a/src/stats.c), from which I have gleaned that the expected function and client usage is as follows:

"When distccd is run with --daemon and --stats, it listens for and accepts TCP connections on port 3633 (unless specified by --stats-port). Upon accepting the connection, the daemon immediately writes a text block of stats as an HTTP reply."

I am using the distcc package in Debian Stretch:

```
[flip]/home/tblack > distcc --version
distcc 3.1 x86_64-pc-linux-gnu
  (protocols 1, 2 and 3) (default port 3632)
  built Aug 23 2015 07:54:48
...
Built with Zeroconf support.
```

Despite the fact that the configuration and init scripts in the Debian Stretch distcc package do not support the --stats or --stats-port option, I have updated my systems to support them, and have verified the stats server running on my distcc server flip works (at least, for some time... see below) from a client issuing:

socat - TCP:flip.local:3633

At some point during compilation, this command starts getting "Connection refused". When I try to restart distccd, the service fails bc distccd is returning error code 102, and /var/log/distccd.log shows:

`distccd[7230] (dcc_listen_by_addr) ERROR: bind of 192.168.100.100:3632 failed: Address already in use
`

At this point I cannot restart distccd because stopping it leaves all 100+ distccd processes alive (I use jobs=200), so the above error is caused by the newly spawned daemons trying to bind to an already-bound to address/port. It all works when `killall distccd` and restart the service, and then I can use it again, but the same problem happens eventually when I compile.

Any advice on what might be going wrong with my usage of the distccd stats server?

Here is the full command line I'm using to start the daemon:

`/usr/bin/distccd --pid-file=/var/run/distccd.pid --log-file=/var/log/distccd.log --daemon --allow 127.0.0.1 --allow 192.168.100.0/24 --listen 192.168.100.100 --nice 10 --jobs 200 --stats --stats-port 3633`

Thanks,
Tim

**Comment by shawnl** [comment]
I've written the most code for does recently and I didn't even know the
stats server existed, so your guess is as good as mine. If we can't find a
use case for the stats server, and it is buggy, perhaps it should be
removed?

**Comment by timblaktu** [comment]
@shawnl, thanks for your comments. Would you be willing to test the stats server yourself with my daemon- and client (socat) commands to see if it breaks for you too? Is there any unit test suite for distcc?

I'm curious if it is breaking for other people as well. Tomorrow I will test various parameters of my build to try to gather info on the issue.

One thing of note is that my client's ~/.distcc/hosts file sets up the distcc server using the ,cpp,lzo suffixes, but the builds my client is doing are not using the pump script. That should be ok, right? (I haven't used pump mode... yet)

**Comment by shawnl** [comment]
> Is there any unit test suite for distcc?
`make check` (its in `test/testdistcc.py`)

**Comment by shawnl** [comment]
Any hints in the log file?

**Comment by shawnl** [comment]
> Is there any unit test suite for distcc?

`make check` (its in `test/testdistcc.py`)


The problem might be in src/prefork.c where if using the stats server kids are never reaped. (but why would they exit?) in `dcc_preforking_parent`

**Comment by timblaktu** [comment]
@shawnl I can reproduce the "connection refused" error without even running a build, i.e. without even opening a single "normal" distcc connection. I just have to start up the daemon (after killing all distccd), run ```watch -n1 socat - TCP:flip.local:3633```, and wait for it to fail.

I've got --verbose on now in the daemon, and below is the clean verbose log output from a failed test run, where I removed all entries, rebooted, then started socat from the client until it died. BTW, I've got 2 questions about the distccd log:
1. Do you know any way to get timestamps in there, or was that a conscious choice to not include them? It's hard for me to tell which events are which without conducting clean experiments like outlined above.
2. distccd doesn't seem to create /var/log/distccd.log (or whatever the log file is set to) if it doesn't exist. Doesn't this seem like a bug to you?

```
distccd[956] (main) chdir to /tmp
distccd[956] (dcc_setup_daemon_path) daemon's PATH is /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
distccd[956] (dcc_listen_by_addr) listening on 192.168.100.100:3632
distccd[956] (dcc_defer_accept) TCP_DEFER_ACCEPT turned on
distccd[956] (dcc_standalone_server) 8 CPUs online on this server
distccd[956] (dcc_standalone_server) allowing up to 200 active jobs
distccd[956] (dcc_ignore_sighup) ignoring SIGHUP
distccd[964] (dcc_detach) setsid to session 964
distccd[964] (dcc_log_daemon_started) preforking daemon started (3.1 x86_64-pc-linux-gnu, built Aug 23 2015 07:54:48)
distccd[964] (dcc_create_kids) up to 1 children
distccd[964] (dcc_create_kids) up to 2 children
.
.
.
distccd[964] (dcc_create_kids) up to 199 children
distccd[964] (dcc_create_kids) up to 200 children
distccd[964] (dcc_listen_by_addr) listening on 192.168.100.100:3633
distccd[964] (dcc_stats_server) HTTP server started on port 3633

distccd[964] (dcc_check_client) connection from 192.168.100.101:60828
distccd[964] (check_address_inet) match client 0x6564a8c0, value 0x64a8c0, mask 0xffffff
distccd[964] (dcc_check_client) connection from 192.168.100.101:60832
distccd[964] (check_address_inet) match client 0x6564a8c0, value 0x64a8c0, mask 0xffffff
distccd[964] (dcc_check_client) connection from 192.168.100.101:60836
distccd[964] (check_address_inet) match client 0x6564a8c0, value 0x64a8c0, mask 0xffffff
.
.
.
distccd[964] (dcc_check_client) connection from 192.168.100.101:33092
distccd[964] (check_address_inet) match client 0x6564a8c0, value 0x64a8c0, mask 0xffffff
distccd[964] (dcc_check_client) connection from 192.168.100.101:33096
```

my client socat connections failed, and the distccd stopped logging anything, or accepting any sort of connections, after a total of 142 stats server connections in my clean test:

```
[flip]/home/tblack > sudo grep "connection from" /var/log/distccd.log | wc -l
142
```

Do you know why --jobs is limited to 200? Is that a limit for _all_ children, or only the non-stats children, or is there no differentiation between stats and non-stats processes?

Thanks for your time.

**Comment by afbjorklund** [comment]
We used the stats server to get the counters, but I never thought that it was hard to use...

Python code:
``` python
            connection = httplib.HTTPConnection('127.0.0.1', 3633)
            request = connection.putrequest('GET', '/distccd')
            connection.endheaders()
            response = connection.getresponse()
            output = response.read()
            connection.close()

```

**Comment by timblaktu** [comment]
Thanks @afbjorklund. Have you ever collected the counters remotely? That's what I'm doing to reproduce this misbehavior. As I wrote above, you don't even have to have a build going concurrently.

Tomorrow, I will try collecting the stats in a few different ways and see if the behavior goes away:
1. run my aforementioned socat command, but locally on the distccd server machine
2. use a python http library to collect stats, both locally and remotely. Perhaps my socat command is doing something the server doesn't like.

Regardless of what works and what doesn't, do you agree that this should be documented, at least somewhere in the man page?

**Comment by timblaktu** [comment]
I get the same result (distccd responds with stats several times, then stops accepting connections, and stops logging anything) when I run my distcc stats-collecting command every second on the distccd server machine: `socat - TCP:localhost:3633`.

Here is the full distccd command the Debian service is running:

`18970 /usr/bin/distccd --pid-file=/var/run/distccd.pid --log-file=/var/log/distccd.log --daemon --verbose --allow 127.0.0.1 --allow 192.168.100.0/24 --listen 127.0.0.1 192.168.100.100 --nice 10 --jobs 200 --stats --stats-port 3633`

Then I rebooted the distcc server machine, waited for all child processes to be spawned (takes 200seconds for my 200 --jobs), and instead ran @afbjorklund 's pythonic stats-collecting code on localhost, in a loop, every second, and got the exact same behavior:

```
[flip]/home/tblack/src > cat ./distcc-stats-test.py
#!/usr/bin/python
import httplib
import sys
import time
distcc_server_addr = "127.0.0.1"
distcc_server_port = 3633
distcc_polling_interval_sec = 1
for i in range(1000000):
    try:
        connection = httplib.HTTPConnection(distcc_server_addr, distcc_server_port)
        request = connection.putrequest('GET', '/distccd')
        connection.endheaders()
        response = connection.getresponse()
        output = response.read()
        print "Distccd stats from server @ %s:%d (i=%d):\n%s" % (distcc_server_addr, distcc_server_port, i, output)
        connection.close()
        time.sleep(distcc_polling_interval_sec)
    except (KeyboardInterrupt, SystemExit):
        sys.exit(1)

[flip]/home/tblack/src > ./distcc-stats-test.py
Distccd stats from server @ 127.0.0.1:3633 (i=0):
argv /distccd
<distccstats>
dcc_tcp_accept 0
dcc_rej_bad_req 0
dcc_rej_overload 0
dcc_compile_ok 0
dcc_compile_error 0
dcc_compile_timeout 0
dcc_cli_disconnect 0
dcc_other 0
dcc_longest_job none
dcc_longest_job_compiler none
dcc_longest_job_time_msecs -1
dcc_max_kids 200
dcc_current_load 2
dcc_load1 0.00
dcc_load2 0.00
dcc_load3 0.00
dcc_num_compiles1 0
dcc_num_compiles2 0
dcc_num_compiles3 0
dcc_num_procstate_D 0
dcc_max_RSS 70696
dcc_max_RSS_name (lightdm-gtk-gre)
dcc_io_rate -1
dcc_free_space 2047 MB
</distccstats>
.
.
. 
. (i=177 was last successful)
Traceback (most recent call last):
  File "./distcc-stats-test.py", line 13, in <module>
    response = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer
```

**I ran this test a few times, locally and remotely, at various polling intervals from 0.1-1sec, and it always failed on i=177.** 

So the good news is I have an extremely reproduceable issue. 

Anyone have an idea what is going on here? It would be very helpful @afbjorklund @shawnl if someone else could confirm this happens on their system as well.

**Comment by afbjorklund** [comment]
I collected the stats locally, using a [Ganglia](http://ganglia.info) module.

**Comment by afbjorklund** [comment]
@timblaktu : why do you accept 200 jobs, with only 8 CPUs ? Doesn't that just build looong queues ?

As you might have seen, the basic rule for jobs is "2 + nCPU", which in your case would be "10".

``` C
    /* By default, allow one job per CPU, plus two for the pot.  The extra
     * ones are started to allow for a bit of extra concurrency so that the
     * machine is not idle waiting for disk or network IO. */
```

But the stats server probably needs revisiting, would be nice if it could be restricted to localhost ?

And those stats connections should probably be handled differently from the normal connections.

**Comment by timblaktu** [comment]
@afbjorklund you're right, there was no good reason to use ```--jobs 200```, and as I've shown I reduced the number which appears to have no effect on the misbehavior.

From what I've experienced, restricting stats listening/reporting to localhost would probably prevent the problem from occurring, however, I would not recommend that course of action. It may be true that not many people are using this feature, but IMO collecting server stats remotely via socket is a pretty basic feature these days. (a la iceccd, memcached, etc..) 

Basically, I got here by implementing a sort of client-side tool like distccmon but to monitor distccd server-side stats during a build, to allow sanity-checking of the buildsystem configuration and performance tuning. I had hoped I could get this info using ```socat - TCP:flip.local:3633```, or even (god forbid) ```ssh flip.local socat - TCP:localhost:3633``` on the client machine, but both of these approaches proved to repro the problem. An alternative workaround would be to reduce my remote stats polling to once before the build starts, a limited number (<137) of times during the build, and once after the build. From what I've seen, this would likely workaround the problem.

Perhaps I can look into how the Ganglia module is doing this to see if there is any clue there. @afbjorklund let me know if you have any insight into this, or pointers to where to find the Ganglia module source code. (Then again, perhaps @afbjorklund has not seen this problem bc the Ganglia module doesn't read the stats as much as I am.)

I'll assume that this problem is not affecting many people since I appear to be the only person to stumble across (and report) a problem that has probably existed for a long time. But I think it should stay open until someone has time to debug it.

**Comment by timblaktu** [comment]
@afbjorklund, congrats, your github is the first hit in a "ganglia distcc" google search!

But, when I search the parent of your forked afbjorklund/ganglia-web repo for "distcc" I get no hits. Let me know if you can provide any leads on the location of the ganglia source code that gets distccd counters. Thanks!

**Comment by afbjorklund** [comment]
It's just a python module, think I showed most of it :-) But I can post it later, sure
