### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by MartB** [distcc/distcc#370]
https://github.com/distcc/distcc/blob/5de24577858687106c27dce1c1ae53edac2f6a6f/include_server/parse_file.py#L275

Errors out in pump mode.
```
checking build system type... Include server: exception occurred, quitting after cleaning up.
------- Include server stack trace -----------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/include_server/include_server.py", line 669, in Main
    server.serve_forever()
  File "/usr/lib/python3.8/socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python3.8/socketserver.py", line 318, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/site-packages/include_server/include_server.py", line 356, in handle
    statistics.StartTiming()
  File "/usr/lib/python3.8/site-packages/include_server/statistics.py", line 65, in StartTiming
    start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
----------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/include_server/include_server.py", line 691, in <module>
    Main()
  File "/usr/lib/python3.8/site-packages/include_server/include_server.py", line 669, in Main
    server.serve_forever()
  File "/usr/lib/python3.8/socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python3.8/socketserver.py", line 318, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/site-packages/include_server/include_server.py", line 356, in handle
    statistics.StartTiming()
  File "/usr/lib/python3.8/site-packages/include_server/statistics.py", line 65, in StartTiming
    start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```
A viable replacement would be `time.process_time()` or even `time.perf_counter()` in these specific scenarios.

**Comment by MartB** [comment]
This is still an issue, can i get any reply on this?

**Comment by ngie-eign** [comment]
> This is still an issue, can i get any reply on this?

I think you can close this issue, right?
