### ISSUE TITLE
Python3.10 pump error

### ISSUE THREAD

**Issue by himekifee** [distcc/distcc#454]
Trying to compile something with pump mode on. Pump exit with stderr shown below
```
WARNING include server: Preprocessing locally. Include server internal error: '<class 'SystemError'>: ("PY_SSIZE_T_CLEAN macro must be defined for '#' formats",)' for translation unit '/home/xxx/xxx/xxx.c'
------- Include server stack trace -----------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/include_server/include_server.py", line 384, in handle
    DoCompilationCommand(cmd, currdir,
  File "/usr/lib/python3.10/site-packages/include_server/include_analyzer.py", line 261, in DoCompilationCommand
    self.ProcessCompilationCommand(currdir, parsed_command))
  File "/usr/lib/python3.10/site-packages/include_server/include_analyzer.py", line 189, in ProcessCompilationCommand
    total_closure.update(self._ProcessFileFromCommandLine(translation_unit,
  File "/usr/lib/python3.10/site-packages/include_server/include_analyzer.py", line 129, in _ProcessFileFromCommandLine
    fpath_resolved_pair, fpath_real = self.build_stat_cache.Resolve(
  File "/usr/lib/python3.10/site-packages/include_server/cache_basics.py", line 779, in Resolve
    if _OsPathIsFile(relpath):
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
----------------------------------------------
```

**Comment by Muha0644** [comment]
I am also having the same issue. 
From what I've seen it's something that python 3.10 broke

**Comment by TornaxO7** [comment]
I have the same issue as well.
